### ISSUE TITLE
Cannot connect to ContentSync services

### ISSUE THREAD

**Issue by jamiefang** [contentsync/SketchContentSync.sketchplugin#36] opened 2017-04-19 11:57 UTC
![image](https://cloud.githubusercontent.com/assets/7001013/25178910/53c8db7e-253a-11e7-9570-7aee1b80c999.png)

How can I fix this?

**Comment by dbrody** [comment] 2017-04-19 22:15
@jamiefang - We are looking into it now. Will update soon.

**Comment by dbrody** [comment] 2017-04-19 23:14
@jamiefang  We're having trouble reproducing this now. Can you confirm it is still happening for you If so, maybe try reinstalling it and see if it still happens. Any information on your system would be great too. Thanks!

**Comment by dbrody** [comment] 2017-04-19 23:37
@jamiefang We continued to look into this and we think we've found the issue. Turns out we updated most links but forgot to update one of the download links on the platform. My guess if you downloaded it through that link.

That link has now been updated and we released a minor update just to ensure the versioning is explicit. Version 0.8.2 is now the most up to date and should fix this issue.

I'm closing this issue now but please follow up if this does not fix the issue.

Also, thanks for your interest in ContentSync. Hope you enjoy using it!

**Closed by dbrody** 2017-04-19 23:37 UTC
